In [12]:
import numpy as np
import pandas as pd
import re
import string

In [13]:
df = pd.read_csv("../dataset/job_descriptions.csv")


In [6]:
df.shape

(1615940, 23)

In [16]:
columns_to_drop = [
    "Qualifications", "Country", "longitude", "latitude", "Work Type",
    "Company Size", "Contact", "Role", "Job Portal", "Benefits",
    "Responsibilities", "Company", "Company Profile","Preference","Contact Person","location","Job Posting Date"
]

df = df.drop(columns=columns_to_drop, errors='ignore')  # 'errors="ignore"' prevents errors if a column is missing
  
df = df.head(50)
df.head(50)


Job Id     Experience Salary Range  \
0   1089843540111562  5 to 15 Years    $59K-$99K   
1    398454096642776  2 to 12 Years   $56K-$116K   
2    481640072963533  0 to 12 Years   $61K-$104K   
3    688192671473044  4 to 11 Years    $65K-$91K   
4    117057806156508  1 to 12 Years    $64K-$87K   
5    116831420231957  4 to 12 Years    $59K-$93K   
6   1292168246729889  3 to 15 Years   $63K-$103K   
7   1498778686197107   2 to 8 Years   $65K-$102K   
8   1680293940995740   2 to 9 Years   $65K-$102K   
9    255627812588102  1 to 10 Years    $60K-$80K   
10  2696958764033354  3 to 10 Years   $57K-$104K   
11  1446194141960546  4 to 12 Years    $64K-$98K   
12  1914121205954296  3 to 15 Years   $65K-$122K   
13   290761760113904   1 to 8 Years    $56K-$86K   
14  1627539131873813   1 to 9 Years    $57K-$98K   
15  2691974960988857  4 to 12 Years   $65K-$100K   
16  2823887164112482  5 to 14 Years    $60K-$83K   
17    76902098772934  0 to 11 Years   $55K-$117K   
18   235216486127884  3 to 12 Years   $55K-$121K   
19   407980927519454   5 to 9 Years   $65K-$128K   
20   940776147258900  0 to 15 Years   $62K-$120K   
21  1524311163188117  0 to 10 Years    $64K-$98K   
22  2508133000944341   1 to 8 Years   $58K-$116K   
23  2808730603865187  2 to 14 Years   $62K-$124K   
24  2277355440844434   3 to 9 Years   $60K-$104K   
25  2263070284964014  4 to 12 Years   $58K-$107K   
26  1504621983937621  5 to 15 Years    $59K-$88K   
27  2425661201998142  4 to 15 Years   $64K-$100K   
28  1361459669383850  0 to 12 Years    $63K-$86K   
29  1355325262915901  2 to 10 Years   $65K-$119K   
30  2020637774150541   4 to 8 Years    $55K-$83K   
31   419221709320780   3 to 8 Years   $65K-$115K   
32   619200804346093  1 to 14 Years   $57K-$121K   
33  2063768239629741  1 to 13 Years    $65K-$82K   
34  1889088294438825   0 to 8 Years   $62K-$130K   
35   981851940397954  3 to 10 Years   $58K-$129K   
36  3023207081599021  0 to 12 Years    $60K-$89K   
37   487916817418719   0 to 8 Years   $64K-$103K   
38  1703785128114382  4 to 12 Years   $57K-$100K   
39  2812077440184777  5 to 10 Years    $58K-$81K   
40  1462699667162772  5 to 14 Years   $56K-$109K   
41  2149248180059910  2 to 13 Years   $55K-$121K   
42  1191707058920608   4 to 9 Years   $62K-$129K   
43  1887042790868742  0 to 10 Years    $65K-$95K   
44   385983883133993  1 to 15 Years    $56K-$82K   
45  1624471339210844  1 to 15 Years    $59K-$80K   
46  1373513885523551   3 to 9 Years   $56K-$109K   
47  2828247805840851  5 to 14 Years   $64K-$130K   
48  2283172037354283   3 to 8 Years    $59K-$89K   
49  1623435902000493   4 to 8 Years    $57K-$97K   

                       Job Title  \
0   Digital Marketing Specialist   
1                  Web Developer   
2             Operations Manager   
3               Network Engineer   
4                  Event Manager   
5                Software Tester   
6                        Teacher   
7                 UX/UI Designer   
8                 UX/UI Designer   
9                Wedding Planner   
10                    QA Analyst   
11           Litigation Attorney   
12           Mechanical Engineer   
13         Network Administrator   
14               Account Manager   
15                 Brand Manager   
16                 Social Worker   
17      Social Media Coordinator   
18    Email Marketing Specialist   
19                 HR Generalist   
20               Legal Assistant   
21            Nurse Practitioner   
22              Account Director   
23             Software Engineer   
24              Purchasing Agent   
25              Purchasing Agent   
26              Sales Consultant   
27                Civil Engineer   
28   Network Security Specialist   
29                  UI Developer   
30             Financial Planner   
31                 Event Planner   
32                  Psychologist   
33           Electrical Designer   
34           Electrical Designer   
35                  Data Analyst   
36              Technical Wri

In [10]:
# Extract min and max experience from the 'experience' column
df[['min_experience', 'max_experience']] = df['Experience'].str.extract(r'(\d+)\s*to\s*(\d+)')

# Convert to numeric (optional)
df['min_experience'] = df['min_experience'].astype(float)
df['max_experience'] = df['max_experience'].astype(float)

# Drop the original 'experience' column
df = df.drop(columns=['Experience'])

# Check the result # Verify the changed
df = df.drop(columns=['max_experience'])
df.head()

Job Id Salary Range                     Job Title  \
0  1089843540111562    $59K-$99K  Digital Marketing Specialist   
1   398454096642776   $56K-$116K                 Web Developer   
2   481640072963533   $61K-$104K            Operations Manager   
3   688192671473044    $65K-$91K              Network Engineer   
4   117057806156508    $64K-$87K                 Event Manager   

                                     Job Description  \
0  Social Media Managers oversee an organizations...   
1  Frontend Web Developers design and implement u...   
2  Quality Control Managers establish and enforce...   
3  Wireless Network Engineers design, implement, ...   
4  A Conference Manager coordinates and manages c...   

                                              skills  min_experience  
0  Social media platforms (e.g., Facebook, Twitte...             5.0  
1  HTML, CSS, JavaScript Frontend frameworks (e.g...             2.0  
2  Quality control processes and methodologies St...             0.0  
3  Wireless network design and architecture Wi-Fi...             4.0  
4  Event planning Conference logistics Budget man...             1.0

In [11]:
df.head(50)

Job Id Salary Range                     Job Title  \
0   1089843540111562    $59K-$99K  Digital Marketing Specialist   
1    398454096642776   $56K-$116K                 Web Developer   
2    481640072963533   $61K-$104K            Operations Manager   
3    688192671473044    $65K-$91K              Network Engineer   
4    117057806156508    $64K-$87K                 Event Manager   
5    116831420231957    $59K-$93K               Software Tester   
6   1292168246729889   $63K-$103K                       Teacher   
7   1498778686197107   $65K-$102K                UX/UI Designer   
8   1680293940995740   $65K-$102K                UX/UI Designer   
9    255627812588102    $60K-$80K               Wedding Planner   
10  2696958764033354   $57K-$104K                    QA Analyst   
11  1446194141960546    $64K-$98K           Litigation Attorney   
12  1914121205954296   $65K-$122K           Mechanical Engineer   
13   290761760113904    $56K-$86K         Network Administrator   
14  1627539131873813    $57K-$98K               Account Manager   
15  2691974960988857   $65K-$100K                 Brand Manager   
16  2823887164112482    $60K-$83K                 Social Worker   
17    76902098772934   $55K-$117K      Social Media Coordinator   
18   235216486127884   $55K-$121K    Email Marketing Specialist   
19   407980927519454   $65K-$128K                 HR Generalist   
20   940776147258900   $62K-$120K               Legal Assistant   
21  1524311163188117    $64K-$98K            Nurse Practitioner   
22  2508133000944341   $58K-$116K              Account Director   
23  2808730603865187   $62K-$124K             Software Engineer   
24  2277355440844434   $60K-$104K              Purchasing Agent   
25  2263070284964014   $58K-$107K              Purchasing Agent   
26  1504621983937621    $59K-$88K              Sales Consultant   
27  2425661201998142   $64K-$100K                Civil Engineer   
28  1361459669383850    $63K-$86K   Network Security Specialist   
29  1355325262915901   $65K-$119K                  UI Developer   
30  2020637774150541    $55K-$83K             Financial Planner   
31   419221709320780   $65K-$115K                 Event Planner   
32   619200804346093   $57K-$121K                  Psychologist   
33  2063768239629741    $65K-$82K           Electrical Designer   
34  1889088294438825   $62K-$130K           Electrical Designer   
35   981851940397954   $58K-$129K                  Data Analyst   
36  3023207081599021    $60K-$89K              Technical Writer   
37   487916817418719   $64K-$103K                UX/UI Designer   
38  1703785128114382   $57K-$100K                Tax Consultant   
39  2812077440184777    $58K-$81K               Software Tester   
40  1462699667162772   $56K-$109K             Account Executive   
41  2149248180059910   $55K-$121K         Systems Administrator   
42  1191707058920608   $62K-$129K              Account Director   
43  1887042790868742    $65K-$95K  Digital Marketing Specialist   
44   385983883133993    $56K-$82K        Database Administrator   
45  1624471339210844    $59K-$80K              Research Analyst   
46  1373513885523551   $56K-$109K              Data Entry Clerk   
47  2828247805840851   $64K-$130K              Registered Nurse   
48  2283172037354283    $59K-$89K                Tax Consultant   
49  1623435902000493    $57K-$97K            Investment Analyst   

                                      Job Description  \
0   Social Media Managers oversee an organizations...   
1   Frontend Web Developers design and implement u...   
2   Quality Control Managers establish and enforce...   
3   Wireless Network Engineers design, implement, ...   
4   A Conference Manager coordinates and manages c...   
5   A Quality Assurance Analyst tests software and...   
6   A Classroom Teacher educates students in a spe...   
7   User Interface Designers focus on the visual a...   
8   Interaction Designers specialize in designing ...   
9   A Wedding Consultant a

In [5]:
# Extract min and max salary from the 'Salary Range' column
df[['min_salary', 'max_salary']] = df['Salary Range'].str.extract(r'(\d+)K?-?(\d+)K?')

# Convert to numeric (optional)
df['min_salary'] = df['min_salary'].astype(float) * 1000  # Convert 'K' to full value
df['max_salary'] = df['max_salary'].astype(float) * 1000  # Convert 'K' to full value

# Drop the original 'Salary Range' column
df = df.drop(columns=['Salary Range'])

# Check the result
df.head()


Job Id                     Job Title  \
0  1089843540111562  Digital Marketing Specialist   
1   398454096642776                 Web Developer   
2   481640072963533            Operations Manager   
3   688192671473044              Network Engineer   
4   117057806156508                 Event Manager   

                                     Job Description  \
0  Social Media Managers oversee an organizations...   
1  Frontend Web Developers design and implement u...   
2  Quality Control Managers establish and enforce...   
3  Wireless Network Engineers design, implement, ...   
4  A Conference Manager coordinates and manages c...   

                                              skills  min_experience  \
0  Social media platforms (e.g., Facebook, Twitte...             5.0   
1  HTML, CSS, JavaScript Frontend frameworks (e.g...             2.0   
2  Quality control processes and methodologies St...             0.0   
3  Wireless network design and architecture Wi-Fi...             4.0   
4  Event planning Conference logistics Budget man...             1.0   

   min_salary  max_salary  
0      5000.0      9000.0  
1      5000.0      6000.0  
2      6000.0      1000.0  
3      6000.0      5000.0  
4      6000.0      4000.0

In [6]:
df.head(50)

Job Id                     Job Title  \
0   1089843540111562  Digital Marketing Specialist   
1    398454096642776                 Web Developer   
2    481640072963533            Operations Manager   
3    688192671473044              Network Engineer   
4    117057806156508                 Event Manager   
5    116831420231957               Software Tester   
6   1292168246729889                       Teacher   
7   1498778686197107                UX/UI Designer   
8   1680293940995740                UX/UI Designer   
9    255627812588102               Wedding Planner   
10  2696958764033354                    QA Analyst   
11  1446194141960546           Litigation Attorney   
12  1914121205954296           Mechanical Engineer   
13   290761760113904         Network Administrator   
14  1627539131873813               Account Manager   
15  2691974960988857                 Brand Manager   
16  2823887164112482                 Social Worker   
17    76902098772934      Social Media Coordinator   
18   235216486127884    Email Marketing Specialist   
19   407980927519454                 HR Generalist   
20   940776147258900               Legal Assistant   
21  1524311163188117            Nurse Practitioner   
22  2508133000944341              Account Director   
23  2808730603865187             Software Engineer   
24  2277355440844434              Purchasing Agent   
25  2263070284964014              Purchasing Agent   
26  1504621983937621              Sales Consultant   
27  2425661201998142                Civil Engineer   
28  1361459669383850   Network Security Specialist   
29  1355325262915901                  UI Developer   
30  2020637774150541             Financial Planner   
31   419221709320780                 Event Planner   
32   619200804346093                  Psychologist   
33  2063768239629741           Electrical Designer   
34  1889088294438825           Electrical Designer   
35   981851940397954                  Data Analyst   
36  3023207081599021              Technical Writer   
37   487916817418719                UX/UI Designer   
38  1703785128114382                Tax Consultant   
39  2812077440184777               Software Tester   
40  1462699667162772             Account Executive   
41  2149248180059910         Systems Administrator   
42  1191707058920608              Account Director   
43  1887042790868742  Digital Marketing Specialist   
44   385983883133993        Database Administrator   
45  1624471339210844              Research Analyst   
46  1373513885523551              Data Entry Clerk   
47  2828247805840851              Registered Nurse   
48  2283172037354283                Tax Consultant   
49  1623435902000493            Investment Analyst   

                                      Job Description  \
0   Social Media Managers oversee an organizations...   
1   Frontend Web Developers design and implement u...   
2   Quality Control Managers establish and enforce...   
3   Wireless Network Engineers design, implement, ...   
4   A Conference Manager coordinates and manages c...   
5   A Quality Assurance Analyst tests software and...   
6   A Classroom Teacher educates students in a spe...   
7   User Interface Designers focus on the visual a...   
8   Interaction Designers specialize in designing ...   
9   A Wedding Consultant assists couples in planni...   
10  Performance Testing Specialists assess the per...   
11  Family Law Attorneys deal with legal matters r...   
12  Mechanical Design Engineers create and develop...   
13  Protect an organizations computer networks and...   
14  A Sales Account Manager is responsible for bui...   
15  A Product Brand Manager focuses on promoting a...   
16  Support students social and emotional well-bei...   
17  Create engaging and relevant content, such as ...   
18  Monitor and improve email deliverability rates...   
19  HR Coordinators assist in HR functions such as...   
20  Provide administrative support to legal profes...   
21  F

In [10]:
df = df.rename(columns={'min_experience': 'experience'})
df.head()

Job Id                     Job Title  \
0  1089843540111562  Digital Marketing Specialist   
1   398454096642776                 Web Developer   
2   481640072963533            Operations Manager   
3   688192671473044              Network Engineer   
4   117057806156508                 Event Manager   

                                     Job Description  \
0  Social Media Managers oversee an organizations...   
1  Frontend Web Developers design and implement u...   
2  Quality Control Managers establish and enforce...   
3  Wireless Network Engineers design, implement, ...   
4  A Conference Manager coordinates and manages c...   

                                              skills  experience  min_salary  \
0  Social media platforms (e.g., Facebook, Twitte...         5.0      5000.0   
1  HTML, CSS, JavaScript Frontend frameworks (e.g...         2.0      5000.0   
2  Quality control processes and methodologies St...         0.0      6000.0   
3  Wireless network design and architecture Wi-Fi...         4.0      6000.0   
4  Event planning Conference logistics Budget man...         1.0      6000.0   

   max_salary  
0      9000.0  
1      6000.0  
2      1000.0  
3      5000.0  
4      4000.0

In [11]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[['min_salary', 'max_salary']] = scaler.fit_transform(df[['min_salary', 'max_salary']])

# Check the result
df.head()

Job Id                     Job Title  \
0  1089843540111562  Digital Marketing Specialist   
1   398454096642776                 Web Developer   
2   481640072963533            Operations Manager   
3   688192671473044              Network Engineer   
4   117057806156508                 Event Manager   

                                     Job Description  \
0  Social Media Managers oversee an organizations...   
1  Frontend Web Developers design and implement u...   
2  Quality Control Managers establish and enforce...   
3  Wireless Network Engineers design, implement, ...   
4  A Conference Manager coordinates and manages c...   

                                              skills  experience  min_salary  \
0  Social media platforms (e.g., Facebook, Twitte...         5.0         0.0   
1  HTML, CSS, JavaScript Frontend frameworks (e.g...         2.0         0.0   
2  Quality control processes and methodologies St...         0.0         1.0   
3  Wireless network design and architecture Wi-Fi...         4.0         1.0   
4  Event planning Conference logistics Budget man...         1.0         1.0   

   max_salary  
0    1.000000  
1    0.666667  
2    0.111111  
3    0.555556  
4    0.444444

In [12]:
# Function to clean text data
def clean_text(text):
    text = str(text).lower()  # Convert to lowercase
    text = re.sub(r'\n', ' ', text)  # Remove newlines
    text = re.sub(r'\[.*?\]', '', text)  # Remove text in brackets
    text = re.sub(r'[%s]' % re.escape(string.punctuation), '', text)  # Remove punctuation
    text = re.sub(r'\w*\d\w*', '', text)  # Remove words with numbers
    text = re.sub(r'\s+', ' ', text)  # Remove extra spaces
    return text.strip()

# Apply cleaning to text columns
text_columns = ['Job Description', 'skills','Job Title']
for col in text_columns:
    df[col] = df[col].apply(clean_text)

# Check the cleaned data
df.head()

Job Id                     Job Title  \
0  1089843540111562  digital marketing specialist   
1   398454096642776                 web developer   
2   481640072963533            operations manager   
3   688192671473044              network engineer   
4   117057806156508                 event manager   

                                     Job Description  \
0  social media managers oversee an organizations...   
1  frontend web developers design and implement u...   
2  quality control managers establish and enforce...   
3  wireless network engineers design implement an...   
4  a conference manager coordinates and manages c...   

                                              skills  experience  min_salary  \
0  social media platforms eg facebook twitter ins...         5.0         0.0   
1  html css javascript frontend frameworks eg rea...         2.0         0.0   
2  quality control processes and methodologies st...         0.0         1.0   
3  wireless network design and architecture wifi ...         4.0         1.0   
4  event planning conference logistics budget man...         1.0         1.0   

   max_salary  
0    1.000000  
1    0.666667  
2    0.111111  
3    0.555556  
4    0.444444

In [22]:
# df[['experience']] = scaler.fit_transform(df[['experience']])
df.to_csv("sampled_file.csv", index=True)

In [24]:
locations = ["Gulshan", "Bashundhara", "Dhanmondi", "Uttara", "Mohakhali", 
             "Tejgaon", "Gazipur", "Tangail", "Panthapath", "Banani", 
             "Agargaon", "Mirpur", "Cantonment", "Khilgaon", "Sylhet"]

# Replace location column with random values from the list
df["location"] = np.random.choice(locations, size=len(df))

In [25]:
df.to_csv("output.csv", index=False)

In [11]:
jobSeeker = pd.read_csv("../dataset/jobseekers_dataset.csv")
jobSeeker.head()

jobseeker_id      name                    email    password   userType  \
0             1  pVgmJLMc  pvgmjlmc716@example.com  t3foaZoo3a  JobSeeker   
1             2  NaeGHBAE  naeghbae228@outlook.com  dfZLrhctNA  JobSeeker   
2             3  LYXuZpPl  lyxuzppl451@outlook.com  2jDd8Nuwih  JobSeeker   
3             4  AFMatgAI  afmatgai260@outlook.com  kf7ZAFxh0f  JobSeeker   
4             5  YlTavfhX  yltavfhx953@example.com  s9v0ypwOna  JobSeeker   

   salaryExpectation  experience                                    skills  \
0           93791.98           6                    data cloud c expressjs   
1          123010.68           4  docker azure graphql tensorflow analysis   
2          108270.30           9                         kubernetes django   
3          140835.67          13                               python html   
4          125268.08           0                   analysis docker pytorch   

        location            position  
0        Chicago   Software Engineer  
1  San Francisco      Data Scientist  
2         Boston      Cloud Engineer  
3        Seattle  Frontend Developer  
4         Denver     DevOps Engineer

In [12]:
# Apply cleaning to text columns
jobSeeker['skills'] = jobSeeker['skills'].apply(clean_text)

# Check the cleaned data
jobSeeker.head()

jobseeker_id      name                    email    password   userType  \
0             1  pVgmJLMc  pvgmjlmc716@example.com  t3foaZoo3a  JobSeeker   
1             2  NaeGHBAE  naeghbae228@outlook.com  dfZLrhctNA  JobSeeker   
2             3  LYXuZpPl  lyxuzppl451@outlook.com  2jDd8Nuwih  JobSeeker   
3             4  AFMatgAI  afmatgai260@outlook.com  kf7ZAFxh0f  JobSeeker   
4             5  YlTavfhX  yltavfhx953@example.com  s9v0ypwOna  JobSeeker   

   salaryExpectation  experience                                    skills  \
0           93791.98           6                    data cloud c expressjs   
1          123010.68           4  docker azure graphql tensorflow analysis   
2          108270.30           9                         kubernetes django   
3          140835.67          13                               python html   
4          125268.08           0                   analysis docker pytorch   

        location            position  
0        Chicago   Software Engineer  
1  San Francisco      Data Scientist  
2         Boston      Cloud Engineer  
3        Seattle  Frontend Developer  
4         Denver     DevOps Engineer

In [13]:
jobSeeker[['expected_salary']] = scaler.fit_transform(jobSeeker[['salaryExpectation']])
jobSeeker.head()

jobseeker_id      name                    email    password   userType  \
0             1  pVgmJLMc  pvgmjlmc716@example.com  t3foaZoo3a  JobSeeker   
1             2  NaeGHBAE  naeghbae228@outlook.com  dfZLrhctNA  JobSeeker   
2             3  LYXuZpPl  lyxuzppl451@outlook.com  2jDd8Nuwih  JobSeeker   
3             4  AFMatgAI  afmatgai260@outlook.com  kf7ZAFxh0f  JobSeeker   
4             5  YlTavfhX  yltavfhx953@example.com  s9v0ypwOna  JobSeeker   

   salaryExpectation  experience                                    skills  \
0           93791.98           6                    data cloud c expressjs   
1          123010.68           4  docker azure graphql tensorflow analysis   
2          108270.30           9                         kubernetes django   
3          140835.67          13                               python html   
4          125268.08           0                   analysis docker pytorch   

        location            position  expected_salary  
0        Chicago   Software Engineer         0.531605  
1  San Francisco      Data Scientist         0.775097  
2         Boston      Cloud Engineer         0.652259  
3        Seattle  Frontend Developer         0.923640  
4         Denver     DevOps Engineer         0.793909

In [19]:
jobSeeker[['experience']] = scaler.fit_transform(jobSeeker[['experience']])


columns_to_drop = [
    "email","password","userType", "location","position","salaryExpectation"
]

jobSeeker = jobSeeker.drop(columns=columns_to_drop, errors='ignore')  # 'errors="ignore"' prevents errors if a column is missing

print(jobSeeker.shape)  
jobSeeker.head()

(100000, 5)


jobseeker_id      name  experience  \
0             1  pVgmJLMc    0.400000   
1             2  NaeGHBAE    0.266667   
2             3  LYXuZpPl    0.600000   
3             4  AFMatgAI    0.866667   
4             5  YlTavfhX    0.000000   

                                     skills  expected_salary  
0                    data cloud c expressjs         0.531605  
1  docker azure graphql tensorflow analysis         0.775097  
2                         kubernetes django         0.652259  
3                               python html         0.923640  
4                   analysis docker pytorch         0.793909

In [21]:
df = df.sample(frac=0.5,random_state=42)
df.head()

Job Id                   Job Title  \
1588445  1595947990438534         procurement manager   
1066007   504627801466818          network technician   
1371425  1354984434257332                veterinarian   
1400710  2126515411643134             product manager   
682216   2448275892372348  email marketing specialist   

                                           Job Description  \
1588445  analyze procurement data identify costsaving o...   
1066007  network support specialists provide technical ...   
1371425  an equine veterinarian specializes in the heal...   
1400710  technical product managers oversee the develop...   
682216   implement and manage marketing automation tool...   

                                                    skills  experience  \
1588445  procurement processes vendor assessment contra...         0.0   
1066007  network troubleshooting it support network con...         0.4   
1371425  equine veterinary medicine horse anatomy and p...         0.6   
1400710  product management principles technical backgr...         1.0   
682216   marketing automation platforms eg marketo pard...         0.2   

         min_salary  max_salary  
1588445         0.0    0.777778  
1066007         1.0    0.111111  
1371425         1.0    0.000000  
1400710         0.0    1.000000  
682216          1.0    0.222222

In [ ]:
from sklearn.preprocessing import MinMaxScaler

# Function to calculate Jaccard similarity for skill matching
def jaccard_similarity(skills1, skills2):
    set1, set2 = set(skills1.split()), set(skills2.split())
    return len(set1 & set2) / len(set1 | set2) if set1 | set2 else 0

# Sample a subset of job posts to speed up computations
jobpost_sample = df.sample(n=min(1000, len(df)), random_state=42)  # Adjust sample size

# Normalize salary and experience differences
scaler = MinMaxScaler()

# Compute skill similarity, experience score, and salary compatibility
interaction_matrix = pd.DataFrame(index=jobSeeker.index, columns=jobpost_sample.index)

for seeker_id, seeker in jobSeeker.iterrows():
    for job_id, job in jobpost_sample.iterrows():
        # Skills Match (60% weight)
        skill_match = jaccard_similarity(seeker["skills"], job["skills"])

        # Experience Score (20% weight) - Closer is better
        experience_diff = abs(seeker["experience"] - job["experience"])
        exp_score = 1 / (1 + experience_diff)  # Normalize

        # Salary Compatibility (20% weight)
        min_salary, max_salary = job["min_salary"], job["max_salary"]
        salary_score = 1 if min_salary <= seeker["expected_salary"] <= max_salary else 0

        # Compute weighted sum
        interaction_score = (0.6 * skill_match) + (0.2 * exp_score) + (0.2 * salary_score)
        interaction_matrix.loc[seeker_id, job_id] = interaction_score

# Convert matrix to float
interaction_matrix = interaction_matrix.astype(float)
interaction_matrix.head()
print("hello")


KeyboardInterrupt: 

In [16]:
interaction_matrix.shape

(100000, 500)

In [17]:
interaction_matrix.head()

108318    7787      1237496   55757     818970    403614    1369376  \
0  0.142857  0.125000  0.125000  0.142857  0.366667  0.142857  0.200000   
1  0.353846  0.117647  0.317647  0.353846  0.381818  0.153846  0.381818   
2  0.337931  0.129032  0.329032  0.337931  0.360000  0.137931  0.390476   
3  0.142641  0.148148  0.348148  0.387879  0.337931  0.121212  0.360000   
4  0.173913  0.108108  0.108108  0.173913  0.390476  0.173913  0.160000   

    447926    272262    1222281  ...   1014946   1359848   1365945   14653    \
0  0.142857  0.342857  0.166667  ...  0.166667  0.366667  0.142857  0.142857   
1  0.353846  0.353846  0.381818  ...  0.181818  0.353846  0.353846  0.153846   
2  0.337931  0.337931  0.360000  ...  0.160000  0.373913  0.337931  0.137931   
3  0.321212  0.321212  0.337931  ...  0.137931  0.390476  0.121212  0.201212   
4  0.173913  0.373913  0.190476  ...  0.190476  0.337931  0.173913  0.173913   

    467431    1578293   309436    1560181   130848    745357   
0  0.200000  0.166667  0.325000  0.142857  0.142857  0.166667  
1  0.181818  0.181818  0.317647  0.153846  0.153846  0.153846  
2  0.190476  0.160000  0.329032  0.137931  0.137931  0.173913  
3  0.160000  0.137931  0.378148  0.181212  0.206926  0.190476  
4  0.160000  0.190476  0.308108  0.173913  0.173913  0.137931  

[5 rows x 500 columns]

In [18]:
interaction_matrix.max()

108318     0.423077
7787       0.200000
1237496    0.400000
55757      0.475000
818970     0.400000
             ...   
1578293    0.200000
309436     0.433333
1560181    0.266667
130848     0.300000
745357     0.200000
Length: 500, dtype: float64

In [20]:
interaction_matrix.isna().sum()

108318     0
7787       0
1237496    0
55757      0
818970     0
          ..
1578293    0
309436     0
1560181    0
130848     0
745357     0
Length: 500, dtype: int64

In [21]:
from scipy.sparse.linalg import svds

# Assuming interaction_matrix is already computed
# Apply Singular Value Decomposition (SVD)
k = min(50, min(interaction_matrix.shape) - 1)  # Number of latent factors
U, sigma, Vt = svds(interaction_matrix, k=k)

# Convert sigma into a diagonal matrix
sigma = np.diag(sigma)

# Reconstruct the predicted interaction matrix
predicted_matrix = np.dot(np.dot(U, sigma), Vt)

# Convert back to a DataFrame
predicted_df = pd.DataFrame(predicted_matrix, 
                            index=interaction_matrix.index, 
                            columns=interaction_matrix.columns)

# Show the top predicted job recommendations for each user
predicted_df.head()


TypeError: type not understood

In [22]:

from scipy.sparse.linalg import svds
from scipy.sparse import csr_matrix  # Convert to sparse matrix

# Ensure all values are numeric (replace NaN with 0)
interaction_matrix = interaction_matrix.apply(pd.to_numeric, errors='coerce').fillna(0)

# Convert to sparse matrix format
interaction_sparse = csr_matrix(interaction_matrix.values)

# Apply Singular Value Decomposition (SVD)
k = min(50, min(interaction_matrix.shape) - 1)  # Number of latent factors
U, sigma, Vt = svds(interaction_sparse, k=k)

# Convert sigma into a diagonal matrix
sigma = np.diag(sigma)

# Reconstruct the predicted interaction matrix
predicted_matrix = np.dot(np.dot(U, sigma), Vt)

# Convert back to a DataFrame
predicted_df = pd.DataFrame(predicted_matrix, 
                            index=interaction_matrix.index, 
                            columns=interaction_matrix.columns)

# Show the top predicted job recommendations for each user
predicted_df.head()


108318    7787      1237496   55757     818970    403614    1369376  \
0  0.142857  0.125000  0.125000  0.142857  0.366667  0.142857  0.200000   
1  0.353846  0.117647  0.317647  0.353846  0.381818  0.153846  0.381818   
2  0.337931  0.129032  0.329032  0.337931  0.360000  0.137931  0.390476   
3  0.142641  0.148148  0.348148  0.387879  0.337931  0.121212  0.360000   
4  0.173913  0.108108  0.108108  0.173913  0.390476  0.173913  0.160000   

    447926    272262    1222281  ...   1014946   1359848   1365945   14653    \
0  0.142857  0.342857  0.166667  ...  0.166667  0.366667  0.142857  0.142857   
1  0.353846  0.353846  0.381818  ...  0.181818  0.353846  0.353846  0.153846   
2  0.337931  0.337931  0.360000  ...  0.160000  0.373913  0.337931  0.137931   
3  0.321212  0.321212  0.337931  ...  0.137931  0.390476  0.121212  0.201212   
4  0.173913  0.373913  0.190476  ...  0.190476  0.337931  0.173913  0.173913   

    467431    1578293   309436    1560181   130848    745357   
0  0.200000  0.166667  0.325000  0.142857  0.142857  0.166667  
1  0.181818  0.181818  0.317647  0.153846  0.153846  0.153846  
2  0.190476  0.160000  0.329032  0.137931  0.137931  0.173913  
3  0.160000  0.137931  0.378148  0.181212  0.206926  0.190476  
4  0.160000  0.190476  0.308108  0.173913  0.173913  0.137931  

[5 rows x 500 columns]

In [24]:
np.savez("svd_model.npz", 
         U=U, 
         sigma=sigma, 
         Vt=Vt, 
         user_index=interaction_matrix.index.values, 
         job_index=interaction_matrix.columns.values)


In [16]:
data = np.load("../model/svd_model.npz")
U = data["U"]
sigma = np.diag(data["sigma"])  # Convert to diagonal matrix
Vt = data["Vt"]
user_index = data["user_index"]
job_index = data["job_index"]

# Convert indices to lists for mapping
user_index = list(user_index)
job_index = list(job_index)

In [19]:
import pandas as pd
import random
import string

# Given set of skills
skills_set = {'ai', 'sql', 'analysis', 'ml', 'azure', 'flask', 'docker', 'java', 'linux', 'tensorflow', 'expressjs', 
              'c', 'graphql', 'react', 'data', 'aws', 'cloud', 'nodejs', 'typescript', 'fastapi', 'css', 'python',
              'kubernetes', 'html', 'javascript', 'pytorch', 'django'}

# Function to generate a random name
def random_name():
    return ''.join(random.choices(string.ascii_uppercase + string.ascii_lowercase, k=8))

# Function to generate a random email
def random_email(name):
    domains = ['gmail.com', 'yahoo.com', 'outlook.com', 'example.com']
    return f"{name.lower()}{random.randint(100,999)}@{random.choice(domains)}"

# Function to generate a random password
def random_password():
    return ''.join(random.choices(string.ascii_letters + string.digits, k=10))

# Function to generate random skills
def random_skills():
    return ' '.join(random.sample(list(skills_set), random.randint(2, 6)))  # Select 2-6 random skills

# Function to generate random experience name
def random_experience():
    positions = ['Software Engineer', 'Data Scientist', 'ML Engineer', 'Backend Developer', 'Frontend Developer', 
                 'Cloud Engineer', 'AI Specialist', 'DevOps Engineer']
    return random.choice(positions)

# Function to generate random location
def random_location():
    locations = ['New York', 'San Francisco', 'Los Angeles', 'Austin', 'Seattle', 'Boston', 'Chicago', 'Denver']
    return random.choice(locations)

# Generate 100,000 job seekers
data = []
for i in range(1, 100001):
    name = random_name()
    email = random_email(name)
    data.append([
        i,  # JobSeeker ID
        name,
        email,
        random_password(),
        'JobSeeker',
        round(random.uniform(30000, 150000), 2),  # Salary Expectation
        random.randint(0, 15),  # Experience in years
        random_skills(),
        random_location(),
        random_experience()
    ])

# Create DataFrame
df = pd.DataFrame(data, columns=['jobseeker_id', 'name', 'email', 'password', 'userType', 'salaryExpectation',
                                 'experience', 'skills', 'location', 'position'])

# Save to CSV
df.to_csv('jobseekers_dataset.csv', index=False)

print("Dataset created successfully: jobseekers_dataset.csv")


Dataset created successfully: jobseekers_dataset.csv


In [17]:
print(U)

[[-3.26659936e-04 -1.85249636e-03 -1.66959319e-03 ...  1.68649835e-03
  -5.31552823e-03 -2.59956858e-03]
 [-4.20264547e-06  3.05206453e-04  6.20212810e-04 ...  2.41160105e-03
   2.24334036e-03 -3.46935359e-03]
 [ 3.90321346e-03 -6.48067049e-05 -4.17361544e-03 ...  5.91878015e-04
   2.12736655e-03 -3.52652958e-03]
 ...
 [ 3.72729905e-04  3.54995928e-03 -2.08341738e-03 ... -4.79315514e-03
  -3.97830416e-03 -2.08142879e-03]
 [ 1.46286709e-03 -2.66684414e-03  4.12292857e-03 ...  1.39813949e-03
   2.06947686e-03 -3.52135057e-03]
 [ 3.13305293e-03 -2.36593961e-03 -3.77996279e-03 ... -4.05450041e-03
  -5.00367175e-03 -2.42424130e-03]]


In [18]:
print(sigma,Vt)

[8.06906887e-14 1.68055951e-13 1.68055951e-13 1.68055951e-13
 1.68055951e-13 1.68055951e-13 1.68055951e-13 2.59354048e-05
 2.76700628e-04 6.54685444e-04 2.13470553e-03 3.69238765e-03
 3.43101838e-02 4.17151149e-02 7.47528486e-02 9.75020519e-02
 1.04651865e-01 1.32575593e-01 1.38588258e-01 1.62785726e-01
 2.13038713e-01 2.57544932e-01 2.66012236e-01 2.72271955e-01
 3.35031355e-01 4.12411860e-01 6.17261589e-01 6.21986962e-01
 2.75138567e+00 3.26997387e+00 3.47770394e+00 5.83595076e+00
 6.22799007e+00 7.62154619e+00 1.15393412e+01 1.37752125e+01
 1.51878716e+01 1.62022374e+01 1.82844874e+01 2.06829113e+01
 2.11389515e+01 3.18884037e+01 6.24208570e+01 6.93420954e+01
 7.52673908e+01 9.22190044e+01 1.29636277e+02 1.63641083e+02
 2.31255294e+02 1.69832265e+03] [[-0.02810091 -0.02482528  0.02986926 ...  0.02486107  0.0464658
  -0.03796568]
 [ 0.01262852  0.01969156  0.00051007 ... -0.00898772 -0.0136236
   0.03227045]
 [-0.07998899 -0.00614693  0.03509194 ...  0.0019755   0.06735564
  -0.00941

In [19]:
print(user_index,job_index)

[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(44), np.int64(45), np.int64(46), np.int64(47), np.int64(48), np.int64(49), np.int64(50), np.int64(51), np.int64(52), np.int64(53), np.int64(54), np.int64(55), np.int64(56), np.int64(57), np.int64(58), np.int64(59), np.int64(60), np.int64(61), np.int64(62), np.int64(63), np.int64(64), np.int64(65), np.int64(66), np.int64(67), np.int64(68), np.int64(69), np.int64(70), np.int64(71), n

(49, 8)


Job Id     Experience Salary Range    location  \
0  1089843540111562  5 to 15 Years    $59K-$99K     Douglas   
1   398454096642776  2 to 12 Years   $56K-$116K    Ashgabat   
2   481640072963533  0 to 12 Years   $61K-$104K       Macao   
3   688192671473044  4 to 11 Years    $65K-$91K  Porto-Novo   
4   117057806156508  1 to 12 Years    $64K-$87K    Santiago   

                      Job Title  \
0  Digital Marketing Specialist   
1                 Web Developer   
2            Operations Manager   
3              Network Engineer   
4                 Event Manager   

                                     Job Description  \
0  Social Media Managers oversee an organizations...   
1  Frontend Web Developers design and implement u...   
2  Quality Control Managers establish and enforce...   
3  Wireless Network Engineers design, implement, ...   
4  A Conference Manager coordinates and manages c...   

                                              skills      
0  Social media platforms (e.g., Facebook, Twitte... NaN  
1  HTML, CSS, JavaScript Frontend frameworks (e.g... NaN  
2  Quality control processes and methodologies St... NaN  
3  Wireless network design and architecture Wi-Fi... NaN  
4  Event planning Conference logistics Budget man... NaN

In [27]:
import numpy as np
import pandas as pd

# Load the saved model
model_data = np.load("../model/svd_model.npz", allow_pickle=True)

# Extract stored matrices
U = model_data["U"]
sigma = model_data["sigma"]
Vt = model_data["Vt"]

# Extract job and user indices
user_index = model_data["user_index"]
job_index = model_data["job_index"]

# Reconstruct the predicted interaction matrix
predicted_matrix = np.dot(np.dot(U, sigma), Vt)

# Convert back to DataFrame
predicted_df = pd.DataFrame(predicted_matrix, index=user_index, columns=job_index)

# Function to get top-N recommended job post IDs for a given user
def get_top_n_jobs(user_id, N=5):
    if user_id not in predicted_df.index:
        return f"User ID {user_id} not found in the dataset."
    
    # Get the user's predicted scores for all jobs
    user_predictions = predicted_df.loc[user_id]
    
    # Get the top-N job IDs with highest scores
    top_job_ids = user_predictions.nlargest(N).index.tolist()
    
    return top_job_ids

# Example usage
user_id = 2  # Replace with an actual job seeker ID
top_jobs = get_top_n_jobs(user_id, N=5)
print("Top recommended job IDs:", top_jobs)


Top recommended job IDs: [241552, 1563016, 215113, 359239, 767154]


[[0.14285714 0.125      0.125      ... 0.14285714 0.14285714 0.16666667]
 [0.35384615 0.11764706 0.31764706 ... 0.15384615 0.15384615 0.15384615]
 [0.33793103 0.12903226 0.32903226 ... 0.13793103 0.13793103 0.17391304]
 ...
 [0.1        0.2        0.2        ... 0.1        0.1        0.14285714]
 [0.34285714 0.125      0.325      ... 0.14285714 0.14285714 0.16666667]
 [0.1025641  0.19047619 0.19047619 ... 0.1025641  0.1025641  0.14814815]]


[[484 298  82 ... 397 329 139]
 [468  46 292 ... 323 139 243]
 [298 424 110 ... 350 329 140]
 [122 238 187 ... 463  20 402]
 [261 201 352 ... 346 362 326]]


[[0.1025641  0.19047619 0.19047619 ... 0.1025641  0.1025641  0.14814815]
 [0.34285714 0.125      0.325      ... 0.14285714 0.14285714 0.16666667]
 [0.1        0.2        0.2        ... 0.1        0.1        0.14285714]
 [0.16       0.11428571 0.11428571 ... 0.16       0.16       0.14814815]
 [0.13333333 0.16666667 0.16666667 ... 0.17426901 0.2034188  0.16666667]]


TypeError: only integer scalar arrays can be converted to a scalar index